-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Cursinho
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Cursinho
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Cursinho` DEFAULT CHARACTER SET utf8 ;
USE `Cursinho` ;

-- -----------------------------------------------------
-- Table `Cursinho`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `UF` CHAR(2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `referencia` TEXT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`pessoa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `dtNascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`CPF` ASC),
  INDEX `fk_pessoa_endereco_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_pessoa_endereco`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `Cursinho`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `matricula` INT NOT NULL,
  `pessoa_idpessoa` INT NOT NULL,
  PRIMARY KEY (`idaluno`),
  INDEX `fk_aluno_pessoa1_idx` (`pessoa_idpessoa` ASC),
  CONSTRAINT `fk_aluno_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `Cursinho`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NULL,
  `ementa` TEXT NULL,
  `cargaHoraria` FLOAT NOT NULL,
  `valor` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`aluno_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`aluno_curso` (
  `aluno_idaluno` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  `dataIngresso` DATE NOT NULL,
  PRIMARY KEY (`aluno_idaluno`, `curso_idcurso`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`curso_idcurso` ASC),
  INDEX `fk_aluno_has_curso_aluno1_idx` (`aluno_idaluno` ASC),
  CONSTRAINT `fk_aluno_has_curso_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `Cursinho`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `Cursinho`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idturma`),
  INDEX `fk_turma_curso1_idx` (`curso_idcurso` ASC),
  CONSTRAINT `fk_turma_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `Cursinho`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`aluno_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`aluno_turma` (
  `aluno_idaluno` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`aluno_idaluno`, `turma_idturma`),
  INDEX `fk_aluno_has_turma_turma1_idx` (`turma_idturma` ASC),
  INDEX `fk_aluno_has_turma_aluno1_idx` (`aluno_idaluno` ASC),
  CONSTRAINT `fk_aluno_has_turma_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `Cursinho`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_turma_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `Cursinho`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`contas_A_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`contas_A_pagar` (
  `idcontas_A_pagar` INT NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `qtdParcelas` INT NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  PRIMARY KEY (`idcontas_A_pagar`),
  INDEX `fk_contas_A_pagar_aluno1_idx` (`aluno_idaluno` ASC),
  CONSTRAINT `fk_contas_A_pagar_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `Cursinho`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`quitada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`quitada` (
  `idpagamento` INT NOT NULL,
  `contas_A_pagar_idcontas_A_pagar` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `data` DATE NOT NULL,
  `tipo_pagamento` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idpagamento`),
  INDEX `fk_pagamento_contas_A_pagar1_idx` (`contas_A_pagar_idcontas_A_pagar` ASC),
  CONSTRAINT `fk_pagamento_contas_A_pagar1`
    FOREIGN KEY (`contas_A_pagar_idcontas_A_pagar`)
    REFERENCES `Cursinho`.`contas_A_pagar` (`idcontas_A_pagar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `salario` FLOAT NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NULL,
  `bonus` FLOAT NULL,
  `cargaHoraria` FLOAT NOT NULL,
  `pessoa_idpessoa` INT NOT NULL,
  `cargo_idCargo` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `fk_Funcionario_pessoa1_idx` (`pessoa_idpessoa` ASC),
  INDEX `fk_Funcionario_Cargo1_idx` (`cargo_idCargo` ASC),
  CONSTRAINT `fk_Funcionario_pessoa1`
    FOREIGN KEY (`pessoa_idpessoa`)
    REFERENCES `Cursinho`.`pessoa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Cargo1`
    FOREIGN KEY (`cargo_idCargo`)
    REFERENCES `Cursinho`.`cargo` (`idcargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cursinho`.`funcionario_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cursinho`.`funcionario_turma` (
  `funcionario_idfuncionario` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`funcionario_idfuncionario`, `turma_idturma`),
  INDEX `fk_Funcionario_has_turma_turma1_idx` (`turma_idturma` ASC),
  INDEX `fk_Funcionario_has_turma_Funcionario1_idx` (`funcionario_idfuncionario` ASC),
  CONSTRAINT `fk_Funcionario_has_turma_Funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `Cursinho`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_has_turma_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `Cursinho`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;